# Generated by Django 2.2.10 on 2021-02-20 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_auto_20210220_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='about_me',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='facebook_link',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='instagram_link',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='linkedin_link',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
