# Generated by Django 3.1.4 on 2021-02-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0007_auto_20210223_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='school_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
    ]
