# Generated by Django 3.1.4 on 2021-02-25 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0009_user_institute2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='institute2',
        ),
    ]
