# Generated by Django 3.1.4 on 2021-02-25 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GyaaniBuddy', '0088_institute'),
        ('user_auth', '0010_remove_user_institute2'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institute2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='GyaaniBuddy.institute'),
        ),
    ]
