# Generated by Django 3.1 on 2020-10-02 19:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('GyaaniBuddy', '0083_delete_news_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_tag_new',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_word', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gyaani_Blogs_new',
            fields=[
                ('gb_id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('views', models.IntegerField(default=0)),
                ('description', models.TextField(default='Description')),
                ('category', models.CharField(max_length=100)),
                ('title', models.TextField(default='Title')),
                ('content', models.TextField(default='content')),
                ('headline', models.TextField(default='headline')),
                ('image', models.ImageField(upload_to='blog_image')),
                ('blog_tags', models.ManyToManyField(to='GyaaniBlog.Blog_tag_new')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GyaaniBuddy.writer')),
            ],
        ),
    ]
