# Generated by Django 3.0 on 2020-12-27 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GyaaniBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gyaani_blogs_new',
            name='slug',
            field=models.SlugField(blank=True, default='defaultslug'),
        ),
    ]
