# Generated by Django 2.2.10 on 2021-01-19 14:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GyaaniBlog', '0004_gyaaniblog'),
    ]

    operations = [
        migrations.AddField(
            model_name='gyaaniblog',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='blogpost_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gyaaniblog',
            name='slug',
            field=models.SlugField(blank=True, max_length=210, unique=True),
        ),
    ]
