# Generated by Django 2.2.10 on 2021-01-19 17:29

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('GyaaniBlog', '0005_auto_20210119_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='gyaaniblog',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog_image'),
        ),
        migrations.AddField(
            model_name='gyaaniblog',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
