# Generated by Django 2.2.10 on 2021-01-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GyaaniBlog', '0006_auto_20210119_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='gyaaniblog',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
