# Generated by Django 2.2.10 on 2021-01-20 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GyaaniBlog', '0007_gyaaniblog_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlledBlogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggested_blogs', models.ManyToManyField(related_name='controlled_suggested_blogs', to='GyaaniBlog.GyaaniBlog')),
                ('top_blogs', models.ManyToManyField(related_name='controlled_top_blogs', to='GyaaniBlog.GyaaniBlog')),
            ],
        ),
    ]
