# Generated by Django 2.2.10 on 2021-01-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('GyaaniBlog', '0008_controlledblogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='controlledblogs',
            name='top_blogs',
        ),
        migrations.AddField(
            model_name='controlledblogs',
            name='suggested_tags',
            field=models.ManyToManyField(related_name='controlled_suggested_tags', to='taggit.Tag'),
        ),
    ]
