# Generated by Django 2.2.10 on 2021-01-20 12:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GyaaniBlog', '0009_auto_20210120_0525'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('votes', models.ManyToManyField(blank=True, related_name='blogdemand_vote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
