# Generated by Django 2.2.10 on 2021-01-20 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('GyaaniBlog', '0010_blogdemand'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdemand',
            name='writer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='blogdemand',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
