# Generated by Django 2.2.10 on 2021-01-20 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GyaaniBlog', '0011_auto_20210120_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdemand',
            name='writer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
