# Generated by Django 2.2.10 on 2021-01-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GyaaniBlog', '0012_auto_20210120_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='gyaaniblog',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
