# Generated by Django 2.2.10 on 2021-01-30 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GyaaniBlog', '0013_gyaaniblog_views'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gyaaniblog',
            options={'ordering': ['-created_at']},
        ),
    ]
