# Generated by Django 2.2.10 on 2021-03-24 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GyaaniBlog', '0014_auto_20210130_0500'),
    ]

    operations = [
        migrations.AddField(
            model_name='gyaani_blogs_new',
            name='video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
