# Generated by Django 2.2.10 on 2021-03-24 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GyaaniBlog', '0015_gyaani_blogs_new_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gyaani_blogs_new',
            name='video',
        ),
    ]
