# Generated by Django 2.2.10 on 2021-03-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GyaaniBlog', '0016_remove_gyaani_blogs_new_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='gyaaniblog',
            name='video',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
